# Generated by Django 5.0.6 on 2024-06-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('net', models.BigIntegerField()),
                ('ex', models.IntegerField()),
                ('sex', models.CharField(max_length=100)),
                ('pet', models.CharField(max_length=100)),
                ('neighbourhood', models.CharField(max_length=100)),
            ],
        ),
    ]
